name: catching artifacts
on: [push]

jobs:
  cahed-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache README file
        uses: actions/cache@v4.0.2
        id: cache-npm
        with:
          path: README.md
          key: ${{runner.os}}-cached
  uncached-artifact:
    runs-on: ubuntu-latest
    needs: cahed-artifact
    steps:
      -  uses: actions/checkout@v4
      -  name: Uncached README file and print
         uses: actions/cache@v4.0.2
         id: cache-npm
         with:
          path: README.md
          key: ${{runner.os}}-cached
      -  run: cat README.md
         
             
    
