name: Caller Workflow

on: [push]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/inputs-workflow-call.yml
    with:
      build_id: 2
      deploy_target: "Amazon S3"
      perform_deploy: true
