name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
      
    steps:
      - name: deploy
        run: |
          echo "hello world ${{EMAIL}} - ${{APY_KEY}} "
