name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production1
      
    steps:
      - name: deploy
        run: |
          echo "hello world $EMAIL"
