name: Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      file-path:
        description: "Path to test script"
        required: true
        default: "test-file.js"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: 
            echo "For otupust"
    outputs:
        results-file: # id of output
        description: "Path to results file"