name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production1
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Deploy to production
        run: | 
          echo $API_KEY
          echo $EMAIL
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL: ${{ vars.EMAIL }}